# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8bfa60876698e80e9c93ee2f02351d83c12ec8f85e9ce78b42181ccfbc068b480240e1155219274922ecf5d6c82aecd6da0b4bfb2c3590723819d873a3a4831

test:
  secret_key_base: dc7a0de6ee967af0b470b56397d70495290529a301edae6f5d6fbd8aa8af4f81d0bf607ff19e716c133ab801bcad3c49d9795e8c8fd89bedb3539fe215b7827d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
